name: my_workout_tracker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^6.2.0
  flutter_riverpod: ^2.0.2
  scaffold_gradient_background: ^1.0.3+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
